// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {service} from '../models';

export function CloseTerminalSession(arg1:string):Promise<void>;

export function CreateCollection(arg1:string):Promise<models.Collection>;

export function CreateEnvironment(arg1:string):Promise<models.Environment>;

export function CreateRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Request>;

export function CreateUntitledRequest():Promise<models.Request>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function Execute(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:any):Promise<service.ResponseResult>;

export function ExportCollection(arg1:string,arg2:string):Promise<string>;

export function GetAvailableShells():Promise<Array<Record<string, string>>>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetEnvironments():Promise<Array<models.Environment>>;

export function ImportFromCurl(arg1:string):Promise<models.Request>;

export function ImportPostman(arg1:string):Promise<models.Collection>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameRequest(arg1:string,arg2:string):Promise<void>;

export function SeedData():Promise<void>;

export function SendTerminalData(arg1:string):Promise<void>;

export function SendTerminalDataToSession(arg1:string,arg2:string):Promise<void>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function SetTerminalSize(arg1:number,arg2:number):Promise<void>;

export function SetTerminalSizeForSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StartTerminalSession():Promise<void>;

export function StartTerminalSessionWithShell(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function UpdateCollection(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function UpdateCollectionsOrder(arg1:Array<string>):Promise<void>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number,arg10:number,arg11:string):Promise<void>;
