// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2, arg3, arg4);
}

export function CreateUntitledRequest() {
  return window['go']['main']['App']['CreateUntitledRequest']();
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function Execute(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['Execute'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportCollection(arg1, arg2) {
  return window['go']['main']['App']['ExportCollection'](arg1, arg2);
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportFromCurl(arg1) {
  return window['go']['main']['App']['ImportFromCurl'](arg1);
}

export function ImportPostman(arg1) {
  return window['go']['main']['App']['ImportPostman'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameRequest(arg1, arg2) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2);
}

export function SeedData() {
  return window['go']['main']['App']['SeedData']();
}

export function SendTerminalData(arg1) {
  return window['go']['main']['App']['SendTerminalData'](arg1);
}

export function SendTerminalDataToSession(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalDataToSession'](arg1, arg2);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function SetTerminalSize(arg1, arg2) {
  return window['go']['main']['App']['SetTerminalSize'](arg1, arg2);
}

export function SetTerminalSizeForSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTerminalSizeForSession'](arg1, arg2, arg3);
}

export function StartTerminalSession() {
  return window['go']['main']['App']['StartTerminalSession']();
}

export function StartTerminalSessionWithShell(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTerminalSessionWithShell'](arg1, arg2, arg3, arg4);
}

export function UpdateCollection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCollectionsOrder(arg1) {
  return window['go']['main']['App']['UpdateCollectionsOrder'](arg1);
}

export function UpdateEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1, arg2, arg3);
}

export function UpdateRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}
